### ISSUE TITLE
Can't set persona profile picture for Messenger

### ISSUE THREAD

**Issue by ntrphongse** [ptnkchat/ptnkchat#12]
Hi there, I have change the **PERSONA_PROFILE_PICTURE** in *Heroky Config Vars*:
![image](https://user-images.githubusercontent.com/57389575/133719605-dc0e5dcf-b06f-4e1d-9e57-f75b803781a7.png)

But the Messenger still display the old one:
![image](https://user-images.githubusercontent.com/57389575/133719690-5aa34234-24bb-431b-b82b-8e1aee6a7956.png)

How can I fix this?

**Comment by hieplpvip** [comment]
You need to manually remove the old one. See [this](https://developers.facebook.com/docs/messenger-platform/send-messages/personas/#remove).
